### ISSUE TITLE
Lumos Smart Bulb - White & Color support

### ISSUE THREAD

**Issue by dmwyatt** [google/python-lakeside#10]
A quick perusal of the code leads me to believe this doesn't support[ Eufy's RGB bulb](https://www.eufylife.com/products/variant/lumos-smart-bulb-white-andamp;-color/T1013121)...so consider this a request to implement support!

Alternatively, some insight into how the API was reverse engineered by @mjg59  and I might submit a PR implementing the support myself.

**Comment by mjg59** [comment]
There should be T1013 support already - is it not working?

**Comment by dmwyatt** [comment]
I don't know, I haven't bought one yet!  

I didn't see any reference to it in the readme, in the HA component or any HA threads so I thought it might not be supported.  

Good to know it is, thanks for responding.
