### ISSUE TITLE
Support for Eufy T1203 Smart Plug (UK)

### ISSUE THREAD

**Issue by jamos77** [google/python-lakeside#12]
Would it be possible to add support for the T1203 Smart Plug (UK) so that it can be used in Home Assistant  along with this and the HA Eufy Component.

**Comment by jamieshaw** [comment]
+1

Black Friday has come; Home Assistant has taken away 😔

**Comment by mjg59** [comment]
Support has been merged, I'll cut a new release so that HA can be updated.

**Comment by jamos77** [comment]
Thanks. Do you need a separate PR creating to add T1203 to the Eufy Dispatch in the HA Eufy component?  https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/eufy.py

**Comment by mjg59** [comment]
Crap, you're right. Thanks!
